api_version = "2026-07"

[[extensions]]
name = "t:name"
handle = "cart-transform-bundle"
type = "function"
uid = "96c6d7ec-66ef-b768-41f5-696ea678bcf8e849fc5c"
description = "t:description"

  [[extensions.targeting]]
  target = "cart.transform.run"
  input_query = "src/cart_transform_run.graphql"
  export = "cart-transform-run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"

  [extensions.ui.paths]
  create = "/"
  details = "/"
